# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bessel_k <- function(z, nu, expon_scaled = FALSE, verbose = 0L) {
    .Call(`_RcppBessel_BesselK`, z, nu, expon_scaled, verbose)
}

bessel_i <- function(z, nu, expon_scaled = FALSE, verbose = 0L) {
    .Call(`_RcppBessel_BesselI`, z, nu, expon_scaled, verbose)
}

bessel_j <- function(z, nu, expon_scaled = FALSE, verbose = 0L) {
    .Call(`_RcppBessel_BesselJ`, z, nu, expon_scaled, verbose)
}

bessel_y <- function(z, nu, expon_scaled = FALSE, verbose = 0L) {
    .Call(`_RcppBessel_BesselY`, z, nu, expon_scaled, verbose)
}

bessel_h <- function(m, z, nu, expon_scaled = FALSE, verbose = 0L) {
    .Call(`_RcppBessel_BesselH`, m, z, nu, expon_scaled, verbose)
}

airy_a <- function(z, deriv = 0L, expon_scaled = FALSE, verbose = 0L) {
    .Call(`_RcppBessel_AiryA`, z, deriv, expon_scaled, verbose)
}

airy_b <- function(z, deriv = 0L, expon_scaled = FALSE, verbose = 0L) {
    .Call(`_RcppBessel_AiryB`, z, deriv, expon_scaled, verbose)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call(`_RcppBessel_RcppExport_registerCCallable`)
})
